version: 2

sources:
  - name: postgres
    schema: public
    tables:
      - name: fitnessdata
        description: "Table containing fitness data"
        columns:
          - name: id
            description: "Unique identifier for each record"
            meta:
              primary-key: true
            tests:
              - unique
              - not_null
          - name: swim
            description: "Distance swam"
          - name: bike
            description: "Distance biked"
          - name: run
            description: "Distance ran"

models:
  - name: fitness_updated_v2
    description: "Fitness updated v2 table"
    columns:
      - name: id
        description: "Unique identifier for each record"
        meta:
          primary-key: true
        tests:
          - unique
          - not_null
      - name: swim
        description: "Distance swam"
      - name: bike
        description: "Distance biked"
      - name: run
        description: "Distance ran"
