name: dbt

on:
  push:
    branches:
      - main

jobs:
  dbt-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-postgres

      - name: Run dbt
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}
        run: dbt run --profiles-dir $DBT_PROFILES_DIR

      - name: submit artifacts to datafold
        run: |
          set -ex
          datafold dbt upload --ci-config-id 396 --run-type ${DATAFOLD_RUN_TYPE} --commit-sha ${GIT_SHA}
        env: # TODO: update your GitHub secrets to include DATAFOLD_APIKEY - done
          DATAFOLD_APIKEY: ${{ secrets.DATAFOLD_APIKEY }}
          DATAFOLD_RUN_TYPE: "${{ 'production' }}"
          GIT_SHA:
            "${{ github.sha }}"
