name: dbt staging

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - "!main"

jobs:
  run:
    runs-on: ubuntu-20.04
    if: ${{ !github.event.pull_request.draft }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-postgres

      - name: install requirements
        run: pip install -q -r requirement.txt

      - name: dbt deps
        run: dbt deps

      - name: dbt build
        run: |
          mkdir -p ./state/${{ github.head_ref }}
          dbt build --profiles-dir ./ --state ./state/${{ github.head_ref }} --target-path ./target/${{ github.head_ref }}
        env: 
          # Update with your PostgreSQL credentials
          POSTGRES_DB_HOST: datafold-project.crbugiiu4j6r.us-east-1.rds.amazonaws.com
          POSTGRES_DB_PORT: 5432
          POSTGRES_DB_NAME: postgres
          POSTGRES_DB_USER: postgres
          POSTGRES_DB_PASSWORD: Training

      - name: submit artifacts to datafold
        run: |
          set -ex
          datafold dbt upload --ci-config-id 397 --run-type ${DATAFOLD_RUN_TYPE} --commit-sha ${GIT_SHA} --target-folder ./target/${{ github.head_ref }}
        env: 
          DATAFOLD_APIKEY: ${{ secrets.DATAFOLD_APIKEY }}
          DATAFOLD_RUN_TYPE: "${{ 'pull_request' }}"
          GIT_SHA: "${{ github.event.pull_request.head.sha }}"
